spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456

# MyBatis配置
mybatis:
  configuration:
    # 开启驼峰命名映射：数据库字段下划线命名 -> Java对象驼峰命名
    map-underscore-to-camel-case: true